"""Canonical platform permission identifiers."""

from enum import StrEnum


class PermissionCode(StrEnum):
    IDENTITY_MANAGE = "IDENTITY_MANAGE"
    WORKSPACE_CREATE = "WORKSPACE_CREATE"
    WORKSPACE_READ = "WORKSPACE_READ"
    WORKSPACE_MANAGE = "WORKSPACE_MANAGE"
    ENTITY_CREATE = "ENTITY_CREATE"
    ENTITY_READ = "ENTITY_READ"
    ENTITY_UPDATE = "ENTITY_UPDATE"
    ENTITY_ARCHIVE = "ENTITY_ARCHIVE"
    RELATIONSHIP_MANAGE = "RELATIONSHIP_MANAGE"
    METADATA_MANAGE = "METADATA_MANAGE"
    FORM_DESIGN = "FORM_DESIGN"
    FORM_SUBMIT = "FORM_SUBMIT"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_READ = "DOCUMENT_READ"
    DOCUMENT_ARCHIVE = "DOCUMENT_ARCHIVE"
    IMPORT_EXECUTE = "IMPORT_EXECUTE"
    PHASE_MANAGE = "PHASE_MANAGE"
    PHASE_LOCK = "PHASE_LOCK"
    PHASE_UNLOCK = "PHASE_UNLOCK"
    REVIEW_MANAGE = "REVIEW_MANAGE"
    DASHBOARD_READ = "DASHBOARD_READ"
    DASHBOARD_MANAGE = "DASHBOARD_MANAGE"
    AUDIT_READ = "AUDIT_READ"
